# Generated by Django 5.2.7 on 2025-11-21 01:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0002_tutoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField(default=True)),
                ('justificada', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='cursos.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['estudiante', 'curso', 'fecha'], name='calificacio_estudia_0d6fe8_idx')],
                'unique_together': {('estudiante', 'curso', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='NotaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evaluacion', models.CharField(choices=[('EXAMEN', 'Examen'), ('PROYECTO', 'Proyecto'), ('PRACTICA', 'Práctica'), ('PARTICIPACION', 'Participación')], default='EXAMEN', max_length=20)),
                ('nombre_evaluacion', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nota', models.DecimalField(decimal_places=2, help_text='Nota del 0 al 10', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('porcentaje', models.DecimalField(decimal_places=2, default=100.0, help_text='Porcentaje que representa en la nota final', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('fecha_evaluacion', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('visible_estudiante', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_academicas', to='cursos.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_academicas', to=settings.AUTH_USER_MODEL)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota Académica',
                'verbose_name_plural': 'Notas Académicas',
                'ordering': ['-fecha_evaluacion'],
                'indexes': [models.Index(fields=['estudiante', 'curso'], name='calificacio_estudia_5301e0_idx'), models.Index(fields=['fecha_evaluacion'], name='calificacio_fecha_e_0555a6_idx')],
            },
        ),
    ]
