# Generated by Django 5.2.7 on 2025-12-02 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_tutoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
    ]
